{% set version = "0.6.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-objectproperties
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/objectProperties_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/objectProperties/objectProperties_{{ version }}.tar.gz
  sha256: cbaa5c7905dd40bde9e4eeb6802680a0dcf3a5f346e0d46a79752251f45d5dbf

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-objectsignals >=0.10.2
  run:
    - r-base
    - r-objectsignals >=0.10.2

test:
  commands:
    - $R -e "library('objectProperties')"           # [not win]
    - "\"%R%\" -e \"library('objectProperties')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=objectProperties
  license: GPL (>= 2)
  summary: Supports the definition of sets of properties on objects. Observers can listen to changes on individual properties or the set as a whole. The properties are meant to be fully self-describing. In support of this, there is a framework for defining enumerated types, as well as other bounded types, as S4 classes.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: objectProperties
# Title: A factory of self-describing properties.
# Description: Supports the definition of sets of properties on objects. Observers can listen to changes on individual properties or the set as a whole. The properties are meant to be fully self-describing. In support of this, there is a framework for defining enumerated types, as well as other bounded types, as S4 classes.
# Author: Tengfei Yin, Michael Lawrence
# Maintainer: Tengfei Yin <yintengfei@gmail.com>
# Depends: R (>= 2.12), methods, objectSignals
# Imports: methods, objectSignals (>= 0.10.2)
# Version: 0.6.5
# License: GPL (>= 2)
# Collate: PropertySet-class.R Enum-class.R comp-classes.R
# Packaged: 2011-12-12 18:35:02 UTC; tengfei
# Repository: CRAN
# Date/Publication: 2011-12-13 08:36:36
# NeedsCompilation: no
